### ISSUE TITLE
Infinite Resources - Does not Work right

### ISSUE THREAD

**Issue by Elfykins** [gqxastg/ACNH-Cheat-Tables#4]
So turning this on shows under the cheat section that I have "99" when looking inventory, but in truth the game only registers as 1, I tried also enabling the max stack size, but it did not work. I think setting the "infinite resources" to 30 would be best (as that is the true max size), it would prevent the game from having issues. Is there a way I could do this myself? I tried to edit the script but could not see any value to change.

**Comment by gqxastg** [comment]
You should edit the script of **_"<- ENABLE AFTER LOADING GAME"_**.
You can see **_98_** at the end of lines **139** and **144**, simply change it to **(the number you want - 1)**.
For example, if you want 30, change it to 29.

In fact, I have never tried to use or update **_"CHEATS"_** section, so that I can't even determine whether the original table is valid. Maybe I will check it later.

**Comment by Elfykins** [comment]
Thanks, I managed to find that and get it working. The stack size one doesn't seem to be working at all, but I changed the value to 30 (the games default stack size) for the infinite resources, and it works perfectly now :)

Unbreakable tools works, so does food and bells, but the inventory stack size does not.
